{
 "title": "NServiceBus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Critical Time by Endpoint ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(nservicebus_queue) (increase(nservicebus_messaging_critical_time_seconds_sum[1m])) / avg by(nservicebus_queue) (increase(nservicebus_messaging_critical_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Time by MessageType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(nservicebus_message_type) (increase(nservicebus_messaging_critical_time_seconds_sum[1m])) / avg by(nservicebus_message_type) (increase(nservicebus_messaging_critical_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Time by Endpoint ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(nservicebus_queue) (increase(nservicebus_messaging_processing_time_seconds_sum[1m])) / avg by(nservicebus_queue) (increase(nservicebus_messaging_processing_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Time by MessageType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(nservicebus_message_type) (increase(nservicebus_messaging_processing_time_seconds_sum[1m])) / avg by(nservicebus_message_type) (increase(nservicebus_messaging_processing_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handling Time by Endpoint ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(nservicebus_queue) (increase(nservicebus_messaging_handler_time_seconds_sum[1m])) / avg by(nservicebus_queue) (increase(nservicebus_messaging_handler_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handling Time by MessageHandler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(nservicebus_message_handler_type) (increase(nservicebus_messaging_handler_time_seconds_sum[1m])) / avg by(nservicebus_message_handler_type) (increase(nservicebus_messaging_handler_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure rate by Endpoint ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(nservicebus_queue) (increase(nservicebus_messaging_failures_total[1m])) * 100/ avg by(nservicebus_queue) (increase(nservicebus_messaging_fetches_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure rate by MessageType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(avg by(nservicebus_message_type) (increase(nservicebus_messaging_failures_total[1m])) * 100) / avg by(nservicebus_message_type) (increase(nservicebus_messaging_fetches_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetched messages per endpoint over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(nservicebus_queue) (increase(nservicebus_messaging_fetches_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed messages per endpoint over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(nservicebus_queue) (increase(nservicebus_messaging_failures_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}